server:
  port: 8083

spring:
  application:
    name: ressource-service
  data:
    mongodb:
      uri: mongodb://pi-mongodb:27017/classe-db

management:
  endpoints:
    web:
      exposure:
        include: health,info