spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpserver:
        websocket:
          max-frame-payload-length: 65536
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true  # Important for OPTIONS handling
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "X-User-Id, X-User-Email, X-User-Role"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=X-Forwarded-Prefix # Critical fix
            - RemoveRequestHeader=Forwarded
        - id: document-service
          uri: http://document-service:8082
          predicates:
            - Path=/documents/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: document-ws
          uri: http://document-service:8082
          predicates:
            - Path=/ws-docs/**
          filters:
            - RewritePath=/ws-docs/(?<segment>.*), /ws-docs/${segment}
        - id: projet-service
          uri: http://projet-service:8083
          predicates:
            - Path=/projet/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: ressource-service
          uri: http://ressource-service:8084
          predicates:
            - Path=/classe/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: ressources-service
          uri: http://ressources-service:8089
          predicates:
            - Path=/ressources/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: taches-service
          uri: http://taches-service:8088
          predicates:
            - Path=/taches/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: chat-service
          uri: http://chat-service:8085
          predicates:
            - Path=/chat/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: chat-ws
          uri: http://chat-service:8085
          predicates:
            - Path=/ws-chat/**
          filters:
            - RewritePath=/ws-chat/(?<segment>.*), /ws-chat/${segment}
        - id: test-route
          uri: forward:/test
          predicates:
            - Path=/
server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
jwt:
  secret-key: "dGhpc2lzYXNlY3JldGtleWZvcmRldmVsb3BtZW50b25seTEyMw==" # Same as user-service