server:
  port: 8083

spring:
  application:
    name: projet-service
  data:
    mongodb:
      uri: mongodb://pi-mongodb:27017/projet-db
    devtools:
      restart:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info