server:
  port: 9000

spring:
  application:
    name: projet-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/projet-test
    devtools:
      restart:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info