server:
  port: 8082

spring:
  application:
    name: document-service
  data:
    mongodb:
      uri: mongodb://pi-mongodb:27017/documents-db  # Use container name instead of localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info